#!/bin/python3

import math
import os
import random
import re
import sys

#https://www.hackerrank.com/challenges/k-factorization/problem

#
# Complete the 'kFactorization' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY A
#
from collections import deque
def bfs(n, A):
    parents_of = dict()
    q = deque()
    q.append(n)
    while q:
        num_elements_at_this_depth = len(q)
        first_seen_at_this_depth = set()

        for i in range(num_elements_at_this_depth):
            v = q.popleft()
            if v == 1:
                    break
            for a in A:
                if v % a == 0:
                    u = v // a
                    if u not in parents_of:
                        first_seen_at_this_depth.add(u)
                        parents_of[u] = []
                        q.append(u)

                    if u in parents_of and u in first_seen_at_this_depth:
                        parents_of[u].append(v)


    return parents_of
def kFactorization(num,flag):
    parents_of = bfs(n, A)
    if 1 not in parents_of:
            return [-1]

    v = 1
    path = []
    while True:
            path.append(str(v))
            if v == n:
                    break
            v = min(parents_of[v])

    return path
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    A = list(map(int, input().rstrip().split()))

    result = kFactorization(n, A)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
